name: lerobot
channels:
  - defaults

dependencies:
  - python=3.10
  - pip

  - pip:
      - torch==2.10.0
      - torchvision==0.25.0
      - accelerate==1.13.0
      - transformers==4.51.3
      - diffusers==0.35.2
      - datasets==4.6.1
      - timm==1.0.25
      - lerobot==0.4.4
