defaults:
  - model: beso
  - _self_

base_output_dir: ./output/train/beso/${now:%Y-%m-%d}/${now:%H-%M-%S}
repo_id: "banana_beso_all"
dataset_path: "/home/zzh/workspace/Robot_learning/datasets/banana_beso_all"
video_backend: "torchcodec"

hydra:
  run:
    dir: ${base_output_dir}/hydra

wandb:
  enable: true
  project: "beso_lerobot"
  entity: null
  mode: "online"

train:
  mode: "scratch"  # scratch | warmstart | resume
  checkpoint_path: null
  resume_config: null
  batch_size: 20
  num_workers: 4
  steps: 40000
  save_freq: 2000
  log_freq: 40
  seed: 1000
  output_dir: ${base_output_dir}/model_outputs
  job_name: "beso_${now:%Y-%m-%d}_${now:%H-%M-%S}"
