defaults:
  - model: beast
  - _self_

base_output_dir: ./output/train/beast/${now:%Y-%m-%d}/${now:%H-%M-%S}
repo_id: "beastf"
dataset_path: "/home/zzh/workspace/Robot_learning/datasets/fold_the_towel_all"
video_backend: "torchcodec"

hydra:
  run:
    dir: ${base_output_dir}/hydra

wandb:
  enable: true
  project: "beast-training"
  entity: null
  mode: "online"

train:
  batch_size: 2
  num_workers: 2
  steps: 40000
  save_freq: 5000
  log_freq: 100
  seed: 42
  device: "cuda"
  output_dir: ${base_output_dir}/model_outputs
  job_name: "beast_${now:%Y-%m-%d}_${now:%H-%M-%S}"
  push_to_hub: false
