_target_: policies.beastf.beastf_config.BeastVLAConfig

use_amp: true
normalization_mapping:
  VISUAL: MEAN_STD
  STATE: MEAN_STD
  ACTION: IDENTITY

vlm_path: "microsoft/Florence-2-base"
vlm_model_name: "bert-base-uncased"
freeze_florence: false
freeze_vision_tower: false
freeze_embeddings_only: false
task: "fold the towel"
prompt_robot_name: "Franka Panda"
prompt_num_arms: 1
prompt_action_space: "7 joint positions + 1 gripper width"
prompt_include_meta: true
image_resize_hw: [224, 224]
image_use_clip_normalization: true

optimizer_lr: 1e-5
optimizer_betas: [0.9, 0.999]
optimizer_eps: 1e-8
optimizer_weight_decay: 1e-4
optimizer_grad_clip_norm: 10
scheduler_warmup_steps: 1000
scheduler_decay_steps: 40000
scheduler_decay_lr: 3e-6

act_window_size: 16
multistep: 16
chunk_size: 16
n_action_steps: 16

num_basis: 6
num_dof: 8
action_dim: 8
gripper_dof: 1
gripper_zero_order: true
update_w_bound: true

text_max_length: 77
tokenizer_max_length: ${.text_max_length}
pad_language_to: "longest"
use_second_view: true
second_view_key: "observation.image.wrist_cam"
use_proprio: false
