repo_id: beastf
dataset_path: /home/jing/zihao_zhang/beastf_datasets/fold_the_towel_all/home/jing/zihao_zhang/fold_the_towel_all
task: "fold_the_towel"
checkpoint_path: /home/jing/lerobot-irl-models/src/outputs

train:
  batch_size: 1 #64
  steps: 2 #40000
  save_freq: 1
  seed: 42
  device: cuda
  num_workers: 0
  log_freq: 100
  output_dir: "./output/beastf/"
  job_name: "beastf_training"
  push_to_hub: false
  #Only pi0/pi05
  gradient_checkpointing: true
  compile_model: false

wandb:
  enable: false
  project: "lerobot-training"
  entity: ""
  mode: "disabled"  # "online", "offline", "disabled"
